In [2]:
import pandas as pd

df = pd.read_csv("./data/boston_housing.csv")
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [3]:
df.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [17]:
boston_mapping = {
    "rm": "Average Number of Rooms",
    "crim": "Crime Rate Per Capita",
    "nox": "Nitric Oxides Concentration (pp10m)",
    "age": "Proportion of Units Built Prior to 1940",
    "dis": "Distance from Employment Centers",
    "rad": "Accessibility to Highways",
    "tax": "Property Tax Rate",
    "ptratio": "Pupil-Teacher Ratio",
}

[{"label": boston_mapping[key], "value": key} for key in boston_mapping.keys()]

[{'label': 'Average Number of Rooms', 'value': 'rm'},
 {'label': 'Crime Rate Per Capita', 'value': 'crim'},
 {'label': 'Nitric Oxides Concentration (pp10m)', 'value': 'nox'},
 {'label': 'Proportion of Units Built Prior to 1940', 'value': 'age'},
 {'label': 'Distance from Employment Centers', 'value': 'dis'},
 {'label': 'Accessibility to Highways', 'value': 'rad'},
 {'label': 'Property Tax Rate', 'value': 'tax'},
 {'label': 'Pupil-Teacher Ratio', 'value': 'ptratio'}]

In [ ]:
import plotly.express as px
value = "rm"
label = "Average number of rooms per dwelling"
fig = px.scatter(df, x=value, y="medv", trendline="ols")
fig.update_traces(
    marker=dict(size=6, color="gray", opacity=0.6), selector=dict(mode="markers")
)
fig.update_traces(line=dict(color="red"), selector=dict(mode="lines"))
fig.update_layout(
    title={
        "text": f"{label} Impact on Median House Price",
        "x": 0.5,
        "xanchor": "center",
    },
    hovermode="closest",
)
results = px.get_trendline_results(fig)
model_results = results.px_fit_results.iloc[0]
slope = model_results.params[1]
intercept = model_results.params[0]
equation = f"Equation of the fitted model is: y = {intercept:.2f} + {slope:.2f}x"
fig.show()
print(equation)

y = -34.67 + 9.10x

In [ ]:
value = "rm"
fig = px.scatter(df, x=value, y="medv")
fig.update_traces(
    marker=dict(size=6, color="gray", opacity=0.6), selector=dict(mode="markers")
)
fig.show()

In [5]:
fig = px.scatter(x=df["rm"], y=df["medv"])
fig.show()

In [18]:
import statsmodels.formula.api as smf

model = smf.ols(
    "medv ~ crim + dis + nox + rm + age + rad + tax + ptratio",
    df,
).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   medv   R-squared:                       0.657
Model:                            OLS   Adj. R-squared:                  0.651
Method:                 Least Squares   F-statistic:                     119.0
Date:                Fri, 10 Oct 2025   Prob (F-statistic):          2.50e-110
Time:                        16:24:55   Log-Likelihood:                -1569.5
No. Observations:                 506   AIC:                             3157.
Df Residuals:                     497   BIC:                             3195.
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     28.4067      5.366      5.294      0.000      17.864      38.949
crim          -0.1834      0.036     -5.028      0.000      -0.255      -0.112
dis           -1.3353      0.200     -6.671      0.000      -1.729      -0.942
nox          -22.8109      4.161     -5.482      0.000     -30.986     -14.636
rm             6.3715      0.392     16.238      0.000       5.601       7.142
age           -0.0477      0.014     -3.386      0.001      -0.075      -0.020
rad            0.2723      0.072      3.767      0.000       0.130       0.414
tax           -0.0126      0.004     -3.340      0.001      -0.020      -0.005
ptratio       -1.1768      0.139     -8.441      0.000      -1.451      -0.903
==============================================================================
Omnibus:                      281.766   Durbin-Watson:                   0.847
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2955.210
Skew:                           2.222   Prob(JB):                         0.00
Kurtosis:                      13.974   Cond. No.                     1.14e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.14e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [7]:
model = smf.ols("medv ~ crim + dis + nox + rm + age + rad + ptratio + lstat", df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   medv   R-squared:                       0.716
Model:                            OLS   Adj. R-squared:                  0.712
Method:                 Least Squares   F-statistic:                     156.9
Date:                Fri, 10 Oct 2025   Prob (F-statistic):          1.05e-130
Time:                        11:49:37   Log-Likelihood:                -1521.5
No. Observations:                 506   AIC:                             3061.
Df Residuals:                     497   BIC:                             3099.
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     41.2721      5.040      8.188      0.000      31.369      51.175
crim          -0.1177      0.034     -3.489      0.001      -0.184      -0.051
dis           -1.2377      0.182     -6.791      0.000      -1.596      -0.880
nox          -21.2486      3.718     -5.716      0.000     -28.553     -13.944
rm             4.0420      0.423      9.562      0.000       3.211       4.873
age            0.0004      0.014      0.032      0.975      -0.026       0.027
rad            0.1206      0.041      2.914      0.004       0.039       0.202
ptratio       -1.1550      0.126     -9.144      0.000      -1.403      -0.907
lstat         -0.5609      0.052    -10.834      0.000      -0.663      -0.459
==============================================================================
Omnibus:                      176.934   Durbin-Watson:                   0.991
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              750.042
Skew:                           1.525   Prob(JB):                    1.35e-163
Kurtosis:                       8.126   Cond. No.                     2.03e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.03e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [8]:
model = smf.ols("medv ~ age", df).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   medv   R-squared:                       0.142
Model:                            OLS   Adj. R-squared:                  0.140
Method:                 Least Squares   F-statistic:                     83.48
Date:                Fri, 10 Oct 2025   Prob (F-statistic):           1.57e-18
Time:                        11:49:37   Log-Likelihood:                -1801.5
No. Observations:                 506   AIC:                             3607.
Df Residuals:                     504   BIC:                             3615.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     30.9787      0.999     31.006      0.000      29.016      32.942
age           -0.1232      0.013     -9.137      0.000      -0.150      -0.097
==============================================================================
Omnibus:                      170.034   Durbin-Watson:                   0.613
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              456.983
Skew:                           1.671   Prob(JB):                    5.85e-100
Kurtosis:                       6.240   Cond. No.                         195.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
df = pd.read_csv("./data/California_Houses.csv")
df.head()

,Median_House_Value,Median_Income,Median_Age,Tot_Rooms,Tot_Bedrooms,Population,Households,Latitude,Longitude,Distance_to_coast,Distance_to_LA,Distance_to_SanDiego,Distance_to_SanJose,Distance_to_SanFrancisco
0,452600.0,8.3252,41,880,129,322,126,37.88,-122.23,9263.040773,556529.158342,735501.806984,67432.517001,21250.213767
1,358500.0,8.3014,21,7099,1106,2401,1138,37.86,-122.22,10225.733072,554279.850069,733236.884360,65049.908574,20880.600400
2,352100.0,7.2574,52,1467,190,496,177,37.85,-122.24,8259.085109,554610.717069,733525.682937,64867.289833,18811.487450
3,341300.0,5.6431,52,1274,235,558,219,37.85,-122.25,7768.086571,555194.266086,734095.290744,65287.138412,18031.047568
4,342200.0,3.8462,52,1627,280,565,259,37.85,-122.25,7768.086571,555194.266086,734095.290744,65287.138412,18031.047568

In [10]:
model = smf.ols(
    "Median_House_Value ~ Median_Income + Median_Age + Tot_Rooms + Tot_Bedrooms + Population + Households + Latitude + Longitude + Distance_to_coast + Distance_to_LA + Distance_to_SanDiego + Distance_to_SanJose + Distance_to_SanFrancisco",
    df,
).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:     Median_House_Value   R-squared:                       0.647
Model:                            OLS   Adj. R-squared:                  0.646
Method:                 Least Squares   F-statistic:                     2902.
Date:                Fri, 10 Oct 2025   Prob (F-statistic):               0.00
Time:                        11:51:43   Log-Likelihood:            -2.5914e+05
No. Observations:               20640   AIC:                         5.183e+05
Df Residuals:                   20626   BIC:                         5.184e+05
Df Model:                          13
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                -1.744e+06   2.35e+05     -7.428      0.000    -2.2e+06   -1.28e+06
Median_Income              3.91e+04    337.093    116.000      0.000    3.84e+04    3.98e+04
Median_Age                 876.7917     45.018     19.477      0.000     788.554     965.030
Tot_Rooms                   -5.6971      0.788     -7.234      0.000      -7.241      -4.153
Tot_Bedrooms               102.9989      6.865     15.003      0.000      89.543     116.455
Population                 -39.8322      1.076    -37.033      0.000     -41.940     -37.724
Households                  47.0091      7.479      6.286      0.000      32.350      61.668
Latitude                 -4.409e+04   2805.416    -15.717      0.000   -4.96e+04   -3.86e+04
Longitude                -2.752e+04   1683.845    -16.342      0.000   -3.08e+04   -2.42e+04
Distance_to_coast           -0.2322      0.020    -11.744      0.000      -0.271      -0.193
Distance_to_LA              -0.1474      0.008    -19.483      0.000      -0.162      -0.133
Distance_to_SanDiego         0.2365      0.028      8.455      0.000       0.182       0.291
Distance_to_SanJose          0.1625      0.023      7.062      0.000       0.117       0.208
Distance_to_SanFrancisco    -0.1396      0.025     -5.677      0.000      -0.188      -0.091
==============================================================================
Omnibus:                     5136.394   Durbin-Watson:                   0.971
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            20329.866
Skew:                           1.191   Prob(JB):                         0.00
Kurtosis:                       7.239   Cond. No.                     3.54e+08
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.54e+08. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [14]:
fig = px.scatter(x=df["Population"], y=df["Median_House_Value"])
fig.show()